source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.0"

target "DeliveryPoint" do
    pod 'SDWebImage','3.8.1'
    pod 'AFNetworking','3.1.0'
    pod 'MJExtension',  '3.0.11'
    pod 'SVProgressHUD','2.0.3'
    pod 'DKNightVersion','2.3.1'
    pod 'Masonry','1.0.1'               #设计约束
    pod 'SDAutoLayout', '2.1.2'         #设计约束，比Masonry更简单
end

